# Configuration on how ReadTheDocs (RTD) builds our documentation
# ref: https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    nodejs: "16"
  commands:
    - pip install -r requirements.txt
    - git pull --recurse-submodules
    - git submodule update --remote --recursive
    - jupyter-book build catalystbook/
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - cp -r catalystbook/_build/html/* $READTHEDOCS_OUTPUT/html/

# Explicitly opt out of trying to build additional formats such as PDF and ePub
formats: []